name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build the Docker image
      run: |
           docker build -t github-repo .
           docker tag github-repo:latest 559050231342.dkr.ecr.apsouth-1.amazonaws.com/github-repo:latest
           docker push 559050231342.dkr.ecr.ap-south-1.amazonaws.com/github-repo:latest
           
